export const homeObjOne = {
    id:'about',
    lightBg:true,
    lightText:false,
    topLine: 'Premium Bank',
    headline:  'Unlimited Transaction with zero fees',
    description:'Get access to our exclusive app that allows you to send unlimited transaction without getting charged any fees',
    buttonLabel:'Get started',
    imgStart:true,
    img: require('../../images/svg-2.svg') ,
    alt: 'Car',
    dark : true,
    primary:true,
    darkText:true,
}
export const homeObjtwo = {
    id:'discover',
    lightBg:false,
    lightText:true,
    topLine: 'Premium Bank',
    headline:  'Unlimited Transaction with zero fees',
    description:'Get access to our exclusive app that allows you to send unlimited transaction without getting charged any fees',
    buttonLabel:'Get started',
    imgStart:true,
    img: require('../../images/img-1.png') ,
    alt: 'Car',
    dark : true,
    primary:true,
    darkText:false,
}